//! # Persistence Receipt Capability Evidence
//!
//! Defines the immutable evidence structure presented during state-resident `rearm()`.
//!
//! ## Invariant
//!
//! A [`PersistenceReceipt`] carries commitment material (`C_receipt`), but grants
//! **no authority on its own**. Authority remains strictly resident in the engine state
//! against which `C_expected` is independently recomputed.

use crate::protocol::{Commitment, PROTOCOL_VERSION};
use core::fmt;

/// External capability evidence presented to authorize state-resident engine rearm.
///
/// This structure holds zero pointers, dynamic dynamic allocations, or executable methods.
/// It is an unprivileged container for evidence generated by an external persistence lifecycle.
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
#[repr(C)]
pub struct PersistenceReceipt {
    /// Protocol version under which this receipt was generated.
    version: u16,

    /// Cryptographic commitment digest $C_{\text{receipt}}$ presented as proof of persistence.
    commitment: Commitment,
}

impl PersistenceReceipt {
    /// Constructs a new [`PersistenceReceipt`] with the current protocol version.
    #[inline]
    pub const fn new(commitment: Commitment) -> Self {
        Self {
            version: PROTOCOL_VERSION,
            commitment,
        }
    }

    /// Constructs a receipt from raw bytes and explicit versioning for deserialization.
    #[inline]
    pub const fn from_raw(version: u16, commitment_bytes: [u8; 32]) -> Self {
        Self {
            version,
            commitment: Commitment::new(commitment_bytes),
        }
    }

    /// Returns the protocol version bound into this receipt.
    #[inline]
    pub const fn version(&self) -> u16 {
        self.version
    }

    /// Returns the cryptographic commitment $C_{\text{receipt}}$ held by this receipt.
    #[inline]
    pub const fn commitment(&self) -> &Commitment {
        &self.commitment
    }
}

impl fmt::Debug for PersistenceReceipt {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("PersistenceReceipt")
            .field("version", &self.version)
            .field("commitment", &self.commitment)
            .finish()
    }
}
